import { Inter } from "next/font/google";
import "./globals.css";
import "../../public/css/main.css";
import Header from "./Common/Header";
import Footer from "./Common/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-white text-ctDeepBlue">
          <Header></Header>
          {children}
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
